version: '3.10'

# docker-compose -f docker-compose.yml build
# docker-compose -f docker-compose.yml up -d
services:
  app:
    build: .
    container_name: flask_reviews
    command: gunicorn --bind 0.0.0.0:5000 run:create_app() # WSGI server
    environment:
      - DATABASE_URL=postgresql://postgres:Daimondi12@db:5432/Flask_app # путь до бд, см. db service
    expose:
      - 5000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Daimondi12
      - POSTGRES_DB=Flask_app
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=maijor18@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=Daimondi12 # если сменить здесь, то нужно удалить контентер
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0 # чтобы не было косяков с nginx лушче в одну сеть с app
      - PGADMIN_LISTEN_PORT=5555
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./static:/home/web/default/static
    depends_on:
      - app
      - pgadmin