"""'initial'

Revision ID: 9167bd31f36c
Revises: 
Create Date: 2022-12-31 13:57:42.833833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9167bd31f36c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Film')
    op.drop_table('Bookmark')
    op.drop_table('Star_Rating_Films')
    op.drop_table('Star_Rating_Books')
    op.drop_table('User')
    op.drop_table('Book')
    op.drop_table('Star_Rating_Games')
    op.drop_table('Game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Game',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Game_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('studio', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('cover', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recently_edit', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Game_pkey')
    )
    op.create_table('Star_Rating_Games',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rating', name='Star_Rating_Games_pkey')
    )
    op.create_table('Book',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Book_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('cover', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recently_edit', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Book_pkey')
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('email_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    sa.UniqueConstraint('email_address', name='User_email_address_key'),
    sa.UniqueConstraint('username', name='User_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Star_Rating_Books',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rating', name='Star_Rating_Books_pkey')
    )
    op.create_table('Star_Rating_Films',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rating', name='Star_Rating_Films_pkey')
    )
    op.create_table('Bookmark',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Bookmark_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('author', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['User.id'], name='Bookmark_owner_fkey'),
    sa.PrimaryKeyConstraint('id', name='Bookmark_pkey')
    )
    op.create_table('Film',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Film_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('producer', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('cover', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recently_edit', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Film_pkey')
    )
    # ### end Alembic commands ###
